-- 코드를 입력하세요
SELECT a.AUTHOR_ID	,a.AUTHOR_NAME	,b.CATEGORY	,SUM(SALES
*PRICE) as TOTAL_SALES
FROM BOOK_SALES as s
JOIN BOOK b on b.BOOK_ID=s.BOOK_ID
join AUTHOR as a on a.AUTHOR_ID=b.AUTHOR_ID
WHERE YEAR(s.SALES_DATE)="2022" and MONTH(s.SALES_DATE)="01" 
GROUP BY AUTHOR_ID ,CATEGORY 
ORDER BY AUTHOR_ID ,CATEGORY DESC